using System;
using System.Buffers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace backend.SourceGenerators;

[Generator]
public class SettingsTreeGenerator : IIncrementalGenerator
{
    private class TargetClassInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public List<string> Keys { get; }

        public TargetClassInfo(string ns, string className, List<string> keys)
        {
            Namespace = ns;
            ClassName = className;
            Keys = keys;
        }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateSettingsTreeAttribute.g.cs",
            SourceText.From(@"namespace backend.SourceGenerators;
[System.AttributeUsage(System.AttributeTargets.Class)]
public class GenerateSettingsTreeAttribute : System.Attribute { }", Encoding.UTF8)));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                (ctx, _) => GetTargetClassInfo(ctx))
            .Where(x => x != null);

        context.RegisterSourceOutput(provider, (ctx, info) =>
        {
            if (info == null || !info.Keys.Any()) return;
            ctx.AddSource($"{info.ClassName}.g.cs", SourceText.From(GenerateSettingsClass(info), Encoding.UTF8));
        });
    }

    private TargetClassInfo? GetTargetClassInfo(GeneratorSyntaxContext context)
    {
        var cds = (ClassDeclarationSyntax)context.Node;

        // 1. 检查特性
        var hasAttr = cds.AttributeLists.Any(al => al.Attributes.Any(a =>
            a.Name.ToString().Contains("GenerateSettingsTree")));
        if (!hasAttr) return null;

        // 2. 获取命名空间
        var ns = "Global";
        var parent = cds.Parent;
        while (parent != null && parent is not NamespaceDeclarationSyntax &&
               parent is not FileScopedNamespaceDeclarationSyntax)
            parent = parent.Parent;

        if (parent is BaseNamespaceDeclarationSyntax nsDecl) ns = nsDecl.Name.ToString();

        // 3. 获取类名
        var className = cds.Identifier.Text;

        // 4. 提取 Keys 数组
        var keysField = cds.Members.OfType<FieldDeclarationSyntax>()
            .FirstOrDefault(f => f.Declaration.Variables.Any(v => v.Identifier.Text == "Keys"));
        var initializer = keysField?.Declaration.Variables.First().Initializer?.Value;
        var keys = initializer?.DescendantTokens()
            .Where(t => t.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StringLiteralToken))
            .Select(t => t.ValueText).ToList();

        return keys != null ? new TargetClassInfo(ns, className, keys) : null;
    }

    private string GenerateSettingsClass(TargetClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using backend.SourceGenerators;"); // 引用 SettingNode 所在的命名空间
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {info.ClassName} {{");

        var root = new Node("");
        foreach (var k in info.Keys)
        {
            var parts = k.Split(':');
            var path = parts[0];
            var type = parts.Length > 1 ? parts[1] : "string";
            var current = root;
            var segments = path.Split('.');
            var runningPrefix = "";

            for (var i = 0; i < segments.Length; i++)
            {
                var segment = segments[i];
                runningPrefix = i == 0 ? segment : $"{runningPrefix}.{segment}";
                if (!current.Children.ContainsKey(segment))
                    current.Children[segment] = new Node(segment) { FullPrefix = runningPrefix };
                current = current.Children[segment];
                if (i == segments.Length - 1)
                {
                    current.IsLeaf = true;
                    current.FullKey = path;
                    current.DataType = type;
                }
            }
        }

        GenerateNodes(sb, root, 1, new List<string>());
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void GenerateNodes(StringBuilder sb, Node node, int indent, List<string> parentPascalNames)
    {
        var space = new string(' ', indent * 4);

        foreach (var child in node.Children.Values)
        {
            var currentPascalName = ToPascalCase(child.Name);
            var currentHierarchy = new List<string>(parentPascalNames) { currentPascalName };

            if (child.IsLeaf)
            {
                var keyWithType = $"{child.FullKey}:{child.DataType}";
                var conversionCode = GenerateDefaultValueConversion(child.DataType, keyWithType, currentPascalName);
                sb.AppendLine(
                    $"{space}public static SettingNode<{child.DataType}> {currentPascalName} {{ get; }} = new(\"{child.FullKey}\", {conversionCode});");
            }
            else
            {
                sb.AppendLine($"{space}public static partial class {currentPascalName} {{");

                GenerateNodes(sb, child, indent + 1, currentHierarchy);

                var localRecordName =
                    (currentHierarchy.Count > 1 ? string.Join("", currentHierarchy.Skip(1)) : currentHierarchy[0]) +
                    "Settings";

                sb.AppendLine(
                    $"{space}    public static Task<IDictionary<string, object?>> GetValuesAsync() => SettingNode.GlobalProvider?.GetValuesByPrefixAsync(\"{child.FullPrefix}\") ?? Task.FromResult((IDictionary<string, object?>)new Dictionary<string, object?>());");

                sb.AppendLine($"{space}    public sealed record {localRecordName}(");
                var directMembers = child.Children.Values.ToList();
                for (var i = 0; i < directMembers.Count; i++)
                {
                    var m = directMembers[i];
                    var mPascal = ToPascalCase(m.Name);
                    if (m.IsLeaf)
                    {
                        sb.Append($"{space}        {m.DataType} {mPascal}");
                    }
                    else
                    {
                        var subClassName = mPascal;
                        var subRecordName = string.Join("", currentHierarchy.Skip(1)) + mPascal + "Settings";
                        sb.Append($"{space}        {subClassName}.{subRecordName}? {mPascal}");
                    }

                    sb.Append($"{(i == directMembers.Count - 1 ? "" : ",")}\n");
                }

                sb.AppendLine($"{space}    );");

                sb.AppendLine(
                    $"{space}    public static async Task<{localRecordName}> GetValuesAsObjectAsync(bool includeSubNodes = true) {{");
                sb.AppendLine($"{space}        var dict = await GetValuesAsync();");
                sb.AppendLine($"{space}        return await GetValuesFromDictAsync(dict, includeSubNodes);");
                sb.AppendLine($"{space}    }}");

                sb.AppendLine(
                    $"{space}    internal static async Task<{localRecordName}> GetValuesFromDictAsync(IDictionary<string, object?> dict, bool includeSubNodes = true) {{");
                sb.AppendLine($"{space}        return new {localRecordName}(");
                for (var i = 0; i < directMembers.Count; i++)
                {
                    var m = directMembers[i];
                    var mName = ToPascalCase(m.Name);
                    if (m.IsLeaf)
                    {
                        sb.AppendLine(
                            $"{space}            ({m.DataType})(dict.TryGetValue(\"{m.FullKey}\", out var v{i}) ? v{i} : default({m.DataType}))!{(i == directMembers.Count - 1 ? "" : ",")}");
                    }
                    else
                    {
                        sb.AppendLine(
                            $"{space}            includeSubNodes ? await {mName}.GetValuesFromDictAsync(dict, includeSubNodes) : null{(i == directMembers.Count - 1 ? "" : ",")}");
                    }
                }

                sb.AppendLine($"{space}        );");
                sb.AppendLine($"{space}    }}");

                sb.AppendLine($"{space}}}");
            }
        }
    }

    /// <summary>
    /// 生成从 DefaultValues 字典读取并转换类型的代码
    /// </summary>
    private static string GenerateDefaultValueConversion(string dataType, string keyWithType, string varName)
    {
        return dataType switch
        {
            "string" =>
                $"SettingRegistry.DefaultValues.TryGetValue(\"{keyWithType}\", out var __dv_{varName}) ? __dv_{varName} as string : default",
            "int" =>
                $"SettingRegistry.DefaultValues.TryGetValue(\"{keyWithType}\", out var __dv_{varName}) && __dv_{varName} is int __int_{varName} ? __int_{varName} : default",
            "bool" =>
                $"SettingRegistry.DefaultValues.TryGetValue(\"{keyWithType}\", out var __dv_{varName}) && __dv_{varName} is bool __bool_{varName} ? __bool_{varName} : default",
            "double" =>
                $"SettingRegistry.DefaultValues.TryGetValue(\"{keyWithType}\", out var __dv_{varName}) && __dv_{varName} is double __double_{varName} ? __double_{varName} : default",
            _ =>
                $"SettingRegistry.DefaultValues.TryGetValue(\"{keyWithType}\", out var __dv_{varName}) ? __dv_{varName} as {dataType} : default"
        };
    }

    public static string ToPascalCase(ReadOnlySpan<char> input)
    {
        if (input.IsEmpty) return string.Empty;

        char[]? rentedArray = null;
        var destination = input.Length <= 16
            ? stackalloc char[input.Length]
            : rentedArray = ArrayPool<char>.Shared.Rent(input.Length);

        try
        {
            var destIndex = 0;
            var upperNext = true;

            for (var i = 0; i < input.Length; i++)
            {
                var curr = input[i];

                if (curr == '_')
                {
                    upperNext = true;
                }
                else if (upperNext)
                {
                    destination[destIndex++] = char.ToUpperInvariant(curr);
                    upperNext = false;
                }
                else
                {
                    destination[destIndex++] = curr;
                }
            }

            return destination.Slice(0, destIndex).ToString();
        }
        finally
        {
            if (rentedArray != null) ArrayPool<char>.Shared.Return(rentedArray);
        }
    }

    private class Node
    {
        public string Name;
        public string? FullPrefix;
        public Dictionary<string, Node> Children = new();
        public bool IsLeaf;
        public string? FullKey;
        public string? DataType;

        public Node(string name)
        {
            Name = name;
        }
    }
}