using System;
using System.Buffers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace backend.SourceGenerators;

[Generator]
public class SettingsTreeGenerator : IIncrementalGenerator
{
    private class TargetClassInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public List<string> Keys { get; }

        public TargetClassInfo(string ns, string className, List<string> keys)
        {
            Namespace = ns;
            ClassName = className;
            Keys = keys;
        }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateSettingsTreeAttribute.g.cs",
            SourceText.From(@"namespace backend.SourceGenerators;
[System.AttributeUsage(System.AttributeTargets.Class)]
public class GenerateSettingsTreeAttribute : System.Attribute { }", Encoding.UTF8)));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: (ctx, _) => GetTargetClassInfo(ctx))
            .Where(x => x != null);

        context.RegisterSourceOutput(provider, (ctx, info) =>
        {
            if (info == null || !info.Keys.Any()) return;
            ctx.AddSource($"{info.ClassName}.g.cs", SourceText.From(GenerateSettingsClass(info), Encoding.UTF8));
        });
    }

    private TargetClassInfo? GetTargetClassInfo(GeneratorSyntaxContext context)
    {
        var cds = (ClassDeclarationSyntax)context.Node;

        // 1. 检查特性
        var hasAttr = cds.AttributeLists.Any(al => al.Attributes.Any(a =>
            a.Name.ToString().Contains("GenerateSettingsTree")));
        if (!hasAttr) return null;

        // 2. 获取命名空间
        string ns = "Global";
        var parent = cds.Parent;
        while (parent != null && parent is not NamespaceDeclarationSyntax &&
               parent is not FileScopedNamespaceDeclarationSyntax)
        {
            parent = parent.Parent;
        }

        if (parent is BaseNamespaceDeclarationSyntax nsDecl) ns = nsDecl.Name.ToString();

        // 3. 获取类名
        string className = cds.Identifier.Text;

        // 4. 提取 Keys 数组
        var keysField = cds.Members.OfType<FieldDeclarationSyntax>()
            .FirstOrDefault(f => f.Declaration.Variables.Any(v => v.Identifier.Text == "Keys"));
        var initializer = keysField?.Declaration.Variables.First().Initializer?.Value;
        var keys = initializer?.DescendantTokens()
            .Where(t => t.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StringLiteralToken))
            .Select(t => t.ValueText).ToList();

        return keys != null ? new TargetClassInfo(ns, className, keys) : null;
    }

    private string GenerateSettingsClass(TargetClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using backend.SourceGenerators;"); // 引用 SettingNode 所在的命名空间
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {info.ClassName} {{");

        var root = new Node("");
        foreach (var k in info.Keys)
        {
            var parts = k.Split(':');
            var path = parts[0];
            var type = parts.Length > 1 ? parts[1] : "string";
            var current = root;
            var segments = path.Split('.');
            var runningPrefix = "";

            for (int i = 0; i < segments.Length; i++)
            {
                var segment = segments[i];
                runningPrefix = i == 0 ? segment : $"{runningPrefix}.{segment}";
                if (!current.Children.ContainsKey(segment))
                    current.Children[segment] = new Node(segment) { FullPrefix = runningPrefix };
                current = current.Children[segment];
                if (i == segments.Length - 1)
                {
                    current.IsLeaf = true;
                    current.FullKey = path;
                    current.DataType = type;
                }
            }
        }

        GenerateNodes(sb, root, 1);
        sb.AppendLine("}");
        return sb.ToString();
    }

private void GenerateNodes(StringBuilder sb, Node node, int indent)
    {
        string space = new string(' ', indent * 4);
        foreach (var child in node.Children.Values)
        {
            var name = ToPascalCase(child.Name);
            if (child.IsLeaf)
            {
                sb.AppendLine($"{space}public static SettingNode<{child.DataType}> {name} {{ get; }} = new(\"{child.FullKey}\");");
            }
            else
            {
                sb.AppendLine($"{space}public static partial class {name} {{");
                sb.AppendLine($"{space}    public static Task<IDictionary<string, object?>> GetValuesAsync() => SettingNode.GlobalProvider?.GetValuesByPrefixAsync(\"{child.FullPrefix}\") ?? Task.FromResult((IDictionary<string, object?>)new Dictionary<string, object?>());");
                sb.AppendLine($"{space}    public readonly record struct Data(");
                var leafNodes = GetRecursiveLeafNodes(child).ToList();
                for (int i = 0; i < leafNodes.Count; i++)
                {
                    var leaf = leafNodes[i];
                    var propertyName = ToPascalCase(leaf.FullKey!.Split('.').Last());
                    sb.Append($"{space}        {leaf.DataType} {propertyName}{(i == leafNodes.Count - 1 ? "" : ",")}\n");
                }
                sb.AppendLine($"{space}    ) {{ }}");

                sb.AppendLine($"{space}    public static async Task<Data> GetValuesAsObjectAsync() {{");
                sb.AppendLine($"{space}        var dict = await GetValuesAsync();");
                sb.AppendLine($"{space}        return new Data(");
                for (int i = 0; i < leafNodes.Count; i++)
                {
                    var leaf = leafNodes[i];
                    var propertyName = ToPascalCase(leaf.FullKey!.Split('.').Last());
                    sb.AppendLine($"{space}        ({leaf.DataType})(dict.TryGetValue(\"{leaf.FullKey}\", out var v{i}) ? v{i} : default({leaf.DataType}))!{(i == leafNodes.Count - 1 ? "" : ",")}");
                }
                sb.AppendLine($"{space}        );");
                sb.AppendLine($"{space}    }}");

                GenerateNodes(sb, child, indent + 1);
                sb.AppendLine($"{space}}}");
            }
        }
    }

    private IEnumerable<Node> GetRecursiveLeafNodes(Node node)
    {
        foreach (var child in node.Children.Values)
        {
            if (child.IsLeaf) yield return child;
            foreach (var recursiveChild in GetRecursiveLeafNodes(child))
            {
                yield return recursiveChild;
            }
        }
    }

    public static string ToPascalCase(ReadOnlySpan<char> input)
    {
        if (input.IsEmpty) return string.Empty;

        char[]? rentedArray = null;
        Span<char> destination = input.Length <= 16
            ? stackalloc char[input.Length]
            : (rentedArray = ArrayPool<char>.Shared.Rent(input.Length));

        try
        {
            int destIndex = 0;
            bool upperNext = true;

            for (int i = 0; i < input.Length; i++)
            {
                char curr = input[i];

                if (curr == '_')
                    upperNext = true;
                else if (upperNext)
                {
                    destination[destIndex++] = char.ToUpperInvariant(curr);
                    upperNext = false;
                }
                else destination[destIndex++] = curr;
            }

            return destination.Slice(0, destIndex).ToString();
        }
        finally
        {
            if (rentedArray != null)
            {
                ArrayPool<char>.Shared.Return(rentedArray);
            }
        }
    }

    private class Node
    {
        public string Name;
        public string? FullPrefix;
        public Dictionary<string, Node> Children = new();
        public bool IsLeaf;
        public string? FullKey;
        public string? DataType;
        public Node(string name) => Name = name;
    }
}